# -*- coding: utf-8 -*-
"""Ejercicio1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dVSWAu3JzgBo_KiG1S2FRHZQAVhBatQ-
"""

print("Hello world!")

"""# ***Hola***"""